### ISSUE TITLE
Invariant Violation: Component is not mounted in the DOM

### ISSUE THREAD

**Issue by SystemParadox** [Pomax/react-component-visibility#6]
Hi. Thanks so much for this great mixin. It's excellent.

I am getting an occasional `Invariant Violation: Component is not mounted in the DOM` from `this.getDOMNode` in `checkComponentVisibility`.

It appears that the rate limit timers are not being cleared when the component is unmounted.

**Comment by SystemParadox** [comment]
Actually the main problem is that the `visibilitychange` listener is not being removed, but the timeout probably needs fixing too.

**Comment by Sapphire64** [comment]
I made a fix in my own repo for this case and wanted to submit PR.

Fix looks like this:

```
    checkComponentVisibility: function() {
      if (!this.isMounted()) {
        return this.disableVisbilityHandling();
      }
      ...
```

But it looks as incorrect fixing, but I didn't managed to find a good way (component will unmount etc didn't worked). Yeah, I've checked your PR, if that helps it's great :)

**Comment by SystemParadox** [comment]
I did consider adding a check for `isMounted()` to make sure, but this is marked as deprecated and really the correct solution is to make sure all the event listeners and timers are cleaned up properly :)
